/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tadsounds.Telas;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import tadsounds.Models.Cliente;
import tadsounds.Models.Instrumento;
import tadsounds.Models.ItemCarrinho;
import tadsounds.Exceptions.ClienteException;
import tadsounds.Exceptions.InstrumentoException;
import tadsounds.Servicos.ServicoCliente;
import tadsounds.Servicos.ServicoInstrumento;
import tadsounds.Servicos.ServicoVenda;

/**
 *
 * @author gabriel
 */
public class Venda extends javax.swing.JInternalFrame {

    EditarCliente editarCliente = new EditarCliente();
    String ultimoCliente = null;
    String ultimoInstrumento = null;

    /**
     * Creates new form FormVenda
     */
    public Venda() {
        initComponents();
        tabelaClientes.getColumnModel().getColumn(0).setMinWidth(0);
        tabelaClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelaClientes.getColumnModel().getColumn(0).setWidth(0);
        tabelaInstrumentos.getColumnModel().getColumn(0).setMinWidth(0);
        tabelaInstrumentos.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelaInstrumentos.getColumnModel().getColumn(0).setWidth(0);
        tabelaCarrinho.getColumnModel().getColumn(0).setMinWidth(0);
        tabelaCarrinho.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelaCarrinho.getColumnModel().getColumn(0).setWidth(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        botaoPesquisarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        botaoSelecionar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fieldInstrumento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaInstrumentos = new javax.swing.JTable();
        botaoPesquisarInstrumento = new javax.swing.JButton();
        botaoAdicionar = new javax.swing.JButton();
        botaoFinalizar = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botaoExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaCarrinho = new javax.swing.JTable();
        botaoAlterarQtde = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboPagamento = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fieldRecebido = new javax.swing.JTextField();
        labelTroco = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botaoCalculaTroco = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));

        jLabel1.setText("Nome:");

        botaoPesquisarCliente.setText("Pesquisar");
        botaoPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarClienteActionPerformed(evt);
            }
        });

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaClientes);

        botaoSelecionar.setText("Selecionar");
        botaoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botaoPesquisarCliente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoSelecionar)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSelecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Instrumento"));

        jLabel4.setText("Instrumento");

        tabelaInstrumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Instrumento", "Estoque", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaInstrumentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaInstrumentos);

        botaoPesquisarInstrumento.setText("Pesquisar");
        botaoPesquisarInstrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarInstrumentoActionPerformed(evt);
            }
        });

        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(fieldInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoPesquisarInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoAdicionar)
                .addGap(19, 19, 19))
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoPesquisarInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoAdicionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoFinalizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botaoFinalizar.setText("FINALIZAR");
        botaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarActionPerformed(evt);
            }
        });

        labelTotal.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelTotal.setText("00,00");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho"));

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        jLabel3.setText("Cliente:");

        labelCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tabelaCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Instrumento", "Quantidade", "Preço", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCarrinho.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tabelaCarrinho);

        botaoAlterarQtde.setText("Alterar Quantidade");
        botaoAlterarQtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarQtdeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoAlterarQtde)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoExcluir))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoAlterarQtde))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("R$");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Forma de Pagamento");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Recebido");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Troco");

        comboPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "Dinheiro", "Débito", "Crédito" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("R$");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("R$");

        labelTroco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTroco.setText("00,00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTroco)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(fieldRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(labelTroco))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setText("Total");

        botaoCalculaTroco.setText("Calcular Troco");
        botaoCalculaTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalculaTrocoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoCalculaTroco))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(botaoFinalizar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(labelTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoCalculaTroco))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void botaoPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarClienteActionPerformed
        boolean resultadoPesquisa = false;
        ultimoCliente = fieldNome.getText();
        try {
            resultadoPesquisa = atualizarCliente();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "A pesquisa não retornou resultados ", "Sem resultados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoPesquisarClienteActionPerformed

    private void botaoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelecionarActionPerformed
        try {
            Cliente clienteVenda = null;
            final int row = tabelaClientes.getSelectedRow();
            if (row >= 0) {
                Integer id = (Integer) tabelaClientes.getValueAt(row, 0);
                clienteVenda = ServicoCliente.obterCliente(id);
                labelCliente.setText(clienteVenda.getNome());
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Não é possível adicionar o cliente",
                    "Erro ao adicionar o cliente", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_botaoSelecionarActionPerformed

    private void botaoPesquisarInstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarInstrumentoActionPerformed
        boolean resultadoPesquisa = false;
        ultimoInstrumento = fieldInstrumento.getText();
        try {
            resultadoPesquisa = atualizarInstrumento();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "A pesquisa não retornou resultados ", "Sem resultados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoPesquisarInstrumentoActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        try {
            Cliente clienteVenda = null;
            boolean clienteSelec = ServicoVenda.verificarClienteSelec(clienteVenda, tabelaClientes);
            if (!clienteSelec) {
                JOptionPane.showMessageDialog(rootPane, "Cliente não selecionado! ",
                        "Cliente",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            int row = tabelaInstrumentos.getSelectedRow();
            DefaultTableModel tabelaInstrModel = ((DefaultTableModel) tabelaInstrumentos.getModel());
            DefaultTableModel tabelaCarrinhoModel = (DefaultTableModel) tabelaCarrinho.getModel();

            boolean verificacao = ServicoVenda.verificarInstrSelec(rootPane, tabelaInstrModel,
                    tabelaCarrinhoModel, row);
            if (verificacao == false && tabelaCarrinho.getValueAt(0, 0) != null) {
                JOptionPane.showMessageDialog(rootPane, "O instrumento já "
                        + "está no carrinho ", "Instrumento indisponível",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (row >= 0) {
                Integer qtdeInstrumento = null;
                String respQtdeInstrumentos = JOptionPane.showInputDialog(this, "Quantas unidades?");
                if (respQtdeInstrumentos == null) {
                    return;
                }
                Instrumento instrumento;
                try {
                    qtdeInstrumento = Integer.parseInt(respQtdeInstrumentos);

                    int rowInstrAdc = tabelaInstrumentos.getSelectedRow();
                    int qtdeEmEstoque = 0;
                    int idQtdeAlterar = (Integer) tabelaInstrumentos.getValueAt(rowInstrAdc, 0);
                    instrumento = ServicoInstrumento.obterInstrumento(idQtdeAlterar);
                    qtdeEmEstoque = instrumento.getQuantidade();

                    if (qtdeInstrumento <= 0) {
                        JOptionPane.showMessageDialog(rootPane, "Quantidade de "
                                + "instrumentos inválida", "Quantidade inválida",
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    } else if (qtdeInstrumento > qtdeEmEstoque) {
                        JOptionPane.showMessageDialog(rootPane, "Quantidade solicitada "
                                + "maior do que em estoque!", "Quantidade inválida",
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Quantidade de "
                            + "instrumentos inválida2", "Quantidade inválida",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                Object[] rowObj = new Object[5];
                DecimalFormat doisForm = new DecimalFormat("#.##");
                float subtotal = instrumento.getPreco() * qtdeInstrumento;
                rowObj[0] = instrumento.getId();
                rowObj[1] = instrumento.getNome();
                rowObj[2] = qtdeInstrumento;
                rowObj[3] = instrumento.getPreco();
                rowObj[4] = subtotal;
                tabelaCarrinhoModel.addRow(rowObj);

                ServicoVenda.atualizarTotalLabel(tabelaCarrinhoModel, tabelaCarrinho, labelTotal);
                ServicoVenda.limpaTabelaInstrumento(fieldInstrumento, tabelaInstrModel);

            } else {
                JOptionPane.showMessageDialog(rootPane, "O instrumento não "
                        + "está disponível ", "Instrumento indisponível",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Não é possível adicionar o instrumento",
                    "Erro ao adicionar o instrumento", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    public void limpaTabela(JTextField field, DefaultTableModel tabelaInstrModel) {
        field.setText("");
        tabelaInstrModel.setRowCount(0);
    }

    private void botaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarActionPerformed
        try {

            tadsounds.Models.Venda venda = new tadsounds.Models.Venda();
            Cliente clienteVenda = null;
            int linhaSelCli = tabelaClientes.getSelectedRow();
            if (linhaSelCli >= 0) {
                clienteVenda = ServicoCliente.
                        obterCliente((Integer) tabelaClientes.getValueAt(linhaSelCli, 0));
            }

            float totalVenda = 0;
            DefaultTableModel tabelaCarrinhoModel = (DefaultTableModel) tabelaCarrinho.getModel();
            DefaultTableModel tabelaClienteModel = (DefaultTableModel) tabelaClientes.getModel();
            if (tabelaCarrinhoModel.getRowCount() > 0) {
                for (int i = 0; i < tabelaCarrinhoModel.getRowCount(); i++) {
                    if (tabelaCarrinho.getValueAt(i, 0) != null) {
                        Instrumento instrumento = ServicoInstrumento.obterInstrumento(
                                (Integer) tabelaCarrinho.getValueAt(i, 0));
                        ItemCarrinho itemCarrinho = new ItemCarrinho();
                        itemCarrinho.setInstrumento(instrumento);
                        itemCarrinho.setQuantidade(
                                (Integer) tabelaCarrinhoModel.getValueAt(i, 2));
                        itemCarrinho.setSubtotal((Float) tabelaCarrinhoModel.getValueAt(i, 4));
                        totalVenda += ((Float) tabelaCarrinhoModel.getValueAt(i, 4));
                        venda.getCarrinho().add(itemCarrinho);
                        venda.setTotal(totalVenda);
                        instrumento.setQuantidade(instrumento.getQuantidade()
                                - (Integer) tabelaCarrinhoModel.getValueAt(i, 2));
                    }
                }
            }

            if (clienteVenda == null || totalVenda == 0) {
                JOptionPane.showMessageDialog(rootPane, "Informar os dados "
                        + "da venda!", "Venda inválida",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            venda.setCliente(clienteVenda);
            Date date = new Date();
            venda.setDate(date);

            if (!ServicoVenda.verificarFormaPgto(comboPagamento)) {
                JOptionPane.showMessageDialog(rootPane, "Forma de pagamento "
                        + "não selecionada!", "Forma de Pagamento",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            String formaPagamento = (String) comboPagamento.getSelectedItem();
            venda.setFormaPagamento(formaPagamento);

            JOptionPane.showMessageDialog(rootPane, "Venda efetuada"
                    + " com sucesso!",
                    "Venda efetuada",
                    JOptionPane.INFORMATION_MESSAGE);

            ServicoVenda.fazerVenda(venda);
            ServicoVenda.limpaTabelaVendas(labelCliente, tabelaCarrinhoModel, fieldNome,
                    tabelaClienteModel, comboPagamento,fieldRecebido, labelTroco);
            ServicoVenda.atualizarTotalLabel(tabelaCarrinhoModel, tabelaCarrinho, labelTotal);
            labelTotal.setText("00,00");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                    "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_botaoFinalizarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        try {
            DefaultTableModel tabelaCarrinhoModel = (DefaultTableModel) tabelaCarrinho.getModel();
            int tabelaRemover = tabelaCarrinho.getSelectedRow();
            if (tabelaCarrinho.getValueAt(tabelaRemover, 0) != null) {
                int opcao = JOptionPane.showConfirmDialog(rootPane, "Confirmar exclusão?",
                        "Exclusão",
                        JOptionPane.INFORMATION_MESSAGE);
                if (opcao == JOptionPane.YES_OPTION) {
                tabelaCarrinhoModel.removeRow(tabelaRemover);
                ServicoVenda.atualizarTotalLabel(tabelaCarrinhoModel, tabelaCarrinho, labelTotal);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Item não selecionado!",
                        "Item",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoAlterarQtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarQtdeActionPerformed
        try {
            DefaultTableModel tabelaCarrinhoModel = (DefaultTableModel) tabelaCarrinho.getModel();
            int tabelaQtdAlterar = tabelaCarrinho.getSelectedRow();
            int qtdeEmEstoque = 0;
            int idQtdeAlterar = (Integer) tabelaCarrinhoModel.getValueAt(tabelaQtdAlterar, 0);
            Instrumento instrumento = ServicoInstrumento.obterInstrumento(idQtdeAlterar);
            qtdeEmEstoque = instrumento.getQuantidade();

            if (tabelaCarrinho.getValueAt(tabelaQtdAlterar, 0) != null) {
                int novaQtde = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Digite a nova quantidade",
                        "Alterar Quantidade",
                        JOptionPane.INFORMATION_MESSAGE));
                if (novaQtde <= qtdeEmEstoque) {
                    tabelaCarrinhoModel.setValueAt(novaQtde, tabelaQtdAlterar, 2);
                    float subtotal = instrumento.getPreco() * novaQtde;
                    tabelaCarrinhoModel.setValueAt(subtotal, tabelaQtdAlterar, 4);
                    ServicoVenda.atualizarTotalLabel(tabelaCarrinhoModel, tabelaCarrinho, labelTotal);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Quantidade solicitada "
                            + "maior do que em estoque!", "Quantidade inválida",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Item não selecionado!",
                        "Item",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {

        }

    }//GEN-LAST:event_botaoAlterarQtdeActionPerformed

    private void botaoCalculaTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalculaTrocoActionPerformed
        try {
            DecimalFormat doisForm = new DecimalFormat("#.##");
            float troco = ServicoVenda.calcularTroco(fieldRecebido,labelTotal);
            float recebido = Float.parseFloat(fieldRecebido.getText().replaceAll(",", "."));
            float totalVenda = Float.parseFloat(labelTotal.getText().replaceAll(",", "."));
            if (fieldRecebido == null || troco < 0) {
                JOptionPane.showMessageDialog(rootPane, "Valor recebido "
                        + "inválido!", "Valor Recebido",
                        JOptionPane.ERROR_MESSAGE);
            } else if (recebido < totalVenda) {
                JOptionPane.showMessageDialog(rootPane, "Valor recebido "
                        + "menor do que o total da venda!", "Valor Recebido",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                labelTroco.setText(String.valueOf(doisForm.format(troco)));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Valor recebido "
                    + "inválido!", "Valor Recebido",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoCalculaTrocoActionPerformed

    public boolean atualizarInstrumento() throws InstrumentoException, Exception {
        List<Instrumento> resultado = ServicoInstrumento.procurarInstrumento(ultimoInstrumento);
        DefaultTableModel model = (DefaultTableModel) tabelaInstrumentos.getModel();
        model.setRowCount(0);
        if (resultado == null || resultado.size() <= 0) {
            return false;
        }
        for (int i = 0; i < resultado.size(); i++) {
            Instrumento instrumento = resultado.get(i);
            if (instrumento != null) {
                Object[] row = new Object[4];
                row[0] = instrumento.getId();
                row[1] = instrumento.getNome();
                row[2] = instrumento.getQuantidade();
                row[3] = instrumento.getPreco();
                model.addRow(row);
            }
        }

        return true;
    }

    public boolean atualizarCliente() throws ClienteException, Exception {
        List<Cliente> resultado = ServicoCliente.procurarCliente(ultimoCliente);
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setRowCount(0);
        if (resultado == null || resultado.size() <= 0) {
            return false;
        }
        for (int i = 0; i < resultado.size(); i++) {
            Cliente cliente = resultado.get(i);
            if (cliente != null) {
                Object[] row = new Object[4];
                row[0] = cliente.getId();
                row[1] = cliente.getNome();
                row[2] = cliente.getCpf();
                row[3] = cliente.getEmail();
                modelo.addRow(row);
            }
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoAlterarQtde;
    private javax.swing.JButton botaoCalculaTroco;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoFinalizar;
    private javax.swing.JButton botaoPesquisarCliente;
    private javax.swing.JButton botaoPesquisarInstrumento;
    private javax.swing.JButton botaoSelecionar;
    private javax.swing.JComboBox<String> comboPagamento;
    private javax.swing.JTextField fieldInstrumento;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldRecebido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTroco;
    private javax.swing.JTable tabelaCarrinho;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTable tabelaInstrumentos;
    // End of variables declaration//GEN-END:variables
}
